[package]
name = "rust_sample_lib"
version = "0.1.0"
authors = ["ezura <yuka.ezura@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rust_sample_lib"
crate-type = ["staticlib", "cdylib"]
